// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYKi8ESa6K7vfpYbjWcUWix4naTT3u5FU',
    appId: '1:584385733362:web:158a67bb0e0fe104b6666b',
    messagingSenderId: '584385733362',
    projectId: 'stockmaster-d4053',
    authDomain: 'stockmaster-d4053.firebaseapp.com',
    storageBucket: 'stockmaster-d4053.firebasestorage.app',
    measurementId: 'G-NHYC4K0JFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxzPPBOB-qb9wNXksjqb-J9aWJ2sLt_Sg',
    appId: '1:584385733362:android:b199d2435dc6be59b6666b',
    messagingSenderId: '584385733362',
    projectId: 'stockmaster-d4053',
    storageBucket: 'stockmaster-d4053.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPM2jWRzUcTgwS1pLcEuCaTmMWQdaTUGc',
    appId: '1:584385733362:ios:727d3b6db6e4084fb6666b',
    messagingSenderId: '584385733362',
    projectId: 'stockmaster-d4053',
    storageBucket: 'stockmaster-d4053.firebasestorage.app',
    iosBundleId: 'com.example.stackmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPM2jWRzUcTgwS1pLcEuCaTmMWQdaTUGc',
    appId: '1:584385733362:ios:727d3b6db6e4084fb6666b',
    messagingSenderId: '584385733362',
    projectId: 'stockmaster-d4053',
    storageBucket: 'stockmaster-d4053.firebasestorage.app',
    iosBundleId: 'com.example.stackmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYKi8ESa6K7vfpYbjWcUWix4naTT3u5FU',
    appId: '1:584385733362:web:a05d771b0e015a92b6666b',
    messagingSenderId: '584385733362',
    projectId: 'stockmaster-d4053',
    authDomain: 'stockmaster-d4053.firebaseapp.com',
    storageBucket: 'stockmaster-d4053.firebasestorage.app',
    measurementId: 'G-7JW20NMSW1',
  );

}